version: '3'
services:

  db:
    # depends_on:
    #   postgres-init:
    #     condition: service_completed_successfully

    image: postgres:14
    ports:
      - '${DB_PORT:?not set}:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  next-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app:cached
    env_file:
      - .env
    restart: always
    tty: true # docker run -t
    ports:
      - ${NEXT_PORT?:Input port for next app}:3000
      - ${PRISMA_STUDIO_PORT?:}:5555
    depends_on:
      - db
volumes:
  db-data:
