FROM node:18


WORKDIR /app

RUN apt update && apt install -y iputils-ping net-tools procps

# for devcontainer
RUN chmod 777 /home

# Install dependencies based on the preferred package manager

# create ./node_modules/.prisma folder

# Next.js collects completely anonymous telemetry data about general usage. Learn more here: https://nextjs.org/telemetry
# Uncomment the following line to disable telemetry at run time
# ENV NEXT_TELEMETRY_DISABLED 1

# Note: Don't expose ports here, Compose will handle that for us

# Start Next.js in development mode based on the preferred package manager
# CMD npm run dev