version: '3'
services:

  db:
    # depends_on:
    #   postgres-init:
    #     condition: service_completed_successfully

    image: postgres:14
    container_name: postgres_next
    ports:
      - '${DB_PORT:?not set}:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile.dev
      # args:
      #   USERNAME: ${USERNAME:?}
      #   GROUPNAME: ${GROUPNAME:?}
      #   UID: ${UID:?}
      #   GID: ${GID:?}
    volumes:
      - .:/app:cached
      - ${HOME?:}/.ssh:/root/.ssh:ro
      # - /etc/passwd:/etc/passwd:ro
      # - /etc/group:/etc/group:ro
      # - /home/ponta/.vscode-server/extensions:/home/ponta/.vscode-server/extensions:ro
    env_file:
      - .env
    restart: always
    tty: true # docker run -t
    ports:
      - ${NEXT_PORT?:Input port for next app}:3000
    depends_on:
      - db
volumes:
  db-data:
