version: '3'
services:

  db:
    image: postgres:14
    container_name: postgres_next
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  next-app:
    container_name: next-app
    build:
      context: .
      dockerfile: Dockerfile.dev

    env_file:
      - .env.prod
    restart: always
    tty: true # docker run -t
    ports:
      - 3000:3000
    depends_on:
      - db
volumes:
  db-data:
